version: 0.0
os: linux
files:
  - source: /root
    destination: /root
hooks:
  AfterInstall:
    - location: afterinstall.sh
      timeout: 100
  ApplicationStart:
    - location: applicationstart.sh
      timeout: 100
